<template><div><h1 id="customer-segmentation-analysis" tabindex="-1"><a class="header-anchor" href="#customer-segmentation-analysis"><span>Customer Segmentation Analysis</span></a></h1>
<div class="knowledge-card">
  <div class="knowledge-card__title">
    <span class="icon">📚</span>Project Overview
  </div>
  <div class="knowledge-card__content">
    <ul>
      <li><strong>Difficulty</strong>: Intermediate</li>
      <li><strong>Type</strong>: Clustering Analysis</li>
      <!-- <li><strong>Estimated Time</strong>: 5-7 hours</li> -->
      <li><strong>Skills</strong>: Data Standardization, K-Means Clustering, Cluster Evaluation, Business Interpretation</li>
      <li><strong>Related Knowledge Module</strong>: <a href="/en/core/clustering/kmeans.html">Clustering Algorithms</a></li>
    </ul>
  </div>
</div>
<h2 id="project-background" tabindex="-1"><a class="header-anchor" href="#project-background"><span>Project Background</span></a></h2>
<p>Customer segmentation is an important strategy for businesses to understand customer behavior and preferences. By grouping similar customers together, companies can develop targeted marketing strategies, personalized product recommendations, and tailored service plans. Traditional segmentation is often based on demographic features (such as age, gender, and income), but modern analysis methods can combine multidimensional data like transaction history, browsing behavior, and interaction patterns to create more refined and meaningful customer groups.</p>
<p>In this project, we will use clustering algorithms to segment customer data from a retailer, identify the characteristics and behavior patterns of different groups, and support business decision-making.</p>
<div class="knowledge-card">
  <div class="knowledge-card__title">
    <span class="icon">💡</span>Did You Know?
  </div>
  <div class="knowledge-card__content">
    <p>RFM analysis is a classic method for customer segmentation, based on three key indicators: Recency, Frequency, and Monetary. This simple yet effective approach is still widely used and can be combined with modern clustering algorithms to create more detailed customer profiles.</p>
  </div>
</div>
<h2 id="dataset-introduction" tabindex="-1"><a class="header-anchor" href="#dataset-introduction"><span>Dataset Introduction</span></a></h2>
<p>The dataset used in this project contains one year of transaction records from an online retailer, with approximately 50,000 transactions and the following fields:</p>
<ul>
<li><strong>CustomerID</strong>: Unique customer identifier</li>
<li><strong>InvoiceNo</strong>: Invoice number</li>
<li><strong>InvoiceDate</strong>: Transaction date and time</li>
<li><strong>StockCode</strong>: Product code</li>
<li><strong>Description</strong>: Product description</li>
<li><strong>Quantity</strong>: Quantity purchased</li>
<li><strong>UnitPrice</strong>: Unit price</li>
<li><strong>Country</strong>: Customer’s country</li>
</ul>
<p>We will extract customer-level features from these transaction records and then apply clustering algorithms for segmentation.</p>
<h2 id="project-objectives" tabindex="-1"><a class="header-anchor" href="#project-objectives"><span>Project Objectives</span></a></h2>
<ol>
<li>Extract customer-level features from transaction data</li>
<li>Apply clustering algorithms such as K-Means to segment customers</li>
<li>Evaluate clustering results and determine the optimal number of clusters</li>
<li>Analyze the characteristics and behavior patterns of different customer groups</li>
<li>Provide business recommendations based on segmentation results</li>
</ol>
<h2 id="implementation-steps" tabindex="-1"><a class="header-anchor" href="#implementation-steps"><span>Implementation Steps</span></a></h2>
<h3 id="step-1-data-loading-and-preprocessing" tabindex="-1"><a class="header-anchor" href="#step-1-data-loading-and-preprocessing"><span>Step 1: Data Loading and Preprocessing</span></a></h3>
<p>First, we load the data and perform the necessary preprocessing.</p>
<div class="language-python line-numbers-mode" data-highlighter="prismjs" data-ext="py"><pre v-pre><code><span class="line"><span class="token keyword">import</span> pandas <span class="token keyword">as</span> pd</span>
<span class="line"><span class="token keyword">import</span> numpy <span class="token keyword">as</span> np</span>
<span class="line"><span class="token keyword">import</span> matplotlib<span class="token punctuation">.</span>pyplot <span class="token keyword">as</span> plt</span>
<span class="line"><span class="token keyword">import</span> seaborn <span class="token keyword">as</span> sns</span>
<span class="line"><span class="token keyword">from</span> datetime <span class="token keyword">import</span> datetime</span>
<span class="line"><span class="token keyword">from</span> sklearn<span class="token punctuation">.</span>preprocessing <span class="token keyword">import</span> StandardScaler</span>
<span class="line"><span class="token keyword">from</span> sklearn<span class="token punctuation">.</span>cluster <span class="token keyword">import</span> KMeans</span>
<span class="line"><span class="token keyword">from</span> sklearn<span class="token punctuation">.</span>metrics <span class="token keyword">import</span> silhouette_score</span>
<span class="line"><span class="token keyword">from</span> sklearn<span class="token punctuation">.</span>decomposition <span class="token keyword">import</span> PCA</span>
<span class="line"><span class="token keyword">import</span> warnings</span>
<span class="line">warnings<span class="token punctuation">.</span>filterwarnings<span class="token punctuation">(</span><span class="token string">'ignore'</span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"><span class="token comment"># Load the data</span></span>
<span class="line">df <span class="token operator">=</span> pd<span class="token punctuation">.</span>read_csv<span class="token punctuation">(</span><span class="token string">'online_retail.csv'</span><span class="token punctuation">,</span> encoding<span class="token operator">=</span><span class="token string">'ISO-8859-1'</span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"><span class="token comment"># View basic information about the data</span></span>
<span class="line"><span class="token keyword">print</span><span class="token punctuation">(</span>df<span class="token punctuation">.</span>info<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token keyword">print</span><span class="token punctuation">(</span>df<span class="token punctuation">.</span>head<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"><span class="token comment"># Data cleaning</span></span>
<span class="line"><span class="token comment"># Remove rows with missing CustomerID</span></span>
<span class="line">df <span class="token operator">=</span> df<span class="token punctuation">.</span>dropna<span class="token punctuation">(</span>subset<span class="token operator">=</span><span class="token punctuation">[</span><span class="token string">'CustomerID'</span><span class="token punctuation">]</span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"><span class="token comment"># Remove cancelled orders (Quantity &lt; 0)</span></span>
<span class="line">df <span class="token operator">=</span> df<span class="token punctuation">[</span>df<span class="token punctuation">[</span><span class="token string">'Quantity'</span><span class="token punctuation">]</span> <span class="token operator">></span> <span class="token number">0</span><span class="token punctuation">]</span></span>
<span class="line"></span>
<span class="line"><span class="token comment"># Remove records with UnitPrice &lt;= 0</span></span>
<span class="line">df <span class="token operator">=</span> df<span class="token punctuation">[</span>df<span class="token punctuation">[</span><span class="token string">'UnitPrice'</span><span class="token punctuation">]</span> <span class="token operator">></span> <span class="token number">0</span><span class="token punctuation">]</span></span>
<span class="line"></span>
<span class="line"><span class="token comment"># Convert CustomerID to integer</span></span>
<span class="line">df<span class="token punctuation">[</span><span class="token string">'CustomerID'</span><span class="token punctuation">]</span> <span class="token operator">=</span> df<span class="token punctuation">[</span><span class="token string">'CustomerID'</span><span class="token punctuation">]</span><span class="token punctuation">.</span>astype<span class="token punctuation">(</span><span class="token builtin">int</span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"><span class="token comment"># Convert InvoiceDate to datetime format</span></span>
<span class="line">df<span class="token punctuation">[</span><span class="token string">'InvoiceDate'</span><span class="token punctuation">]</span> <span class="token operator">=</span> pd<span class="token punctuation">.</span>to_datetime<span class="token punctuation">(</span>df<span class="token punctuation">[</span><span class="token string">'InvoiceDate'</span><span class="token punctuation">]</span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"><span class="token comment"># Create a TotalAmount column</span></span>
<span class="line">df<span class="token punctuation">[</span><span class="token string">'TotalAmount'</span><span class="token punctuation">]</span> <span class="token operator">=</span> df<span class="token punctuation">[</span><span class="token string">'Quantity'</span><span class="token punctuation">]</span> <span class="token operator">*</span> df<span class="token punctuation">[</span><span class="token string">'UnitPrice'</span><span class="token punctuation">]</span></span>
<span class="line"></span>
<span class="line"><span class="token comment"># View the cleaned data</span></span>
<span class="line"><span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">"Shape of cleaned data:"</span><span class="token punctuation">,</span> df<span class="token punctuation">.</span>shape<span class="token punctuation">)</span></span>
<span class="line"><span class="token keyword">print</span><span class="token punctuation">(</span>df<span class="token punctuation">.</span>describe<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"><span class="token comment"># View the number of customers per country</span></span>
<span class="line">country_counts <span class="token operator">=</span> df<span class="token punctuation">.</span>groupby<span class="token punctuation">(</span><span class="token string">'Country'</span><span class="token punctuation">)</span><span class="token punctuation">[</span><span class="token string">'CustomerID'</span><span class="token punctuation">]</span><span class="token punctuation">.</span>nunique<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span>sort_values<span class="token punctuation">(</span>ascending<span class="token operator">=</span><span class="token boolean">False</span><span class="token punctuation">)</span></span>
<span class="line">plt<span class="token punctuation">.</span>figure<span class="token punctuation">(</span>figsize<span class="token operator">=</span><span class="token punctuation">(</span><span class="token number">12</span><span class="token punctuation">,</span> <span class="token number">6</span><span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line">country_counts<span class="token punctuation">.</span>plot<span class="token punctuation">(</span>kind<span class="token operator">=</span><span class="token string">'bar'</span><span class="token punctuation">)</span></span>
<span class="line">plt<span class="token punctuation">.</span>title<span class="token punctuation">(</span><span class="token string">'Number of Customers by Country'</span><span class="token punctuation">)</span></span>
<span class="line">plt<span class="token punctuation">.</span>xlabel<span class="token punctuation">(</span><span class="token string">'Country'</span><span class="token punctuation">)</span></span>
<span class="line">plt<span class="token punctuation">.</span>ylabel<span class="token punctuation">(</span><span class="token string">'Number of Customers'</span><span class="token punctuation">)</span></span>
<span class="line">plt<span class="token punctuation">.</span>xticks<span class="token punctuation">(</span>rotation<span class="token operator">=</span><span class="token number">45</span><span class="token punctuation">)</span></span>
<span class="line">plt<span class="token punctuation">.</span>tight_layout<span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">plt<span class="token punctuation">.</span>show<span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="step-2-feature-extraction-rfm-analysis" tabindex="-1"><a class="header-anchor" href="#step-2-feature-extraction-rfm-analysis"><span>Step 2: Feature Extraction - RFM Analysis</span></a></h3>
<p>Next, we use the RFM method to extract customer-level features from the transaction data.</p>
<div class="language-python line-numbers-mode" data-highlighter="prismjs" data-ext="py"><pre v-pre><code><span class="line"><span class="token comment"># Set the analysis snapshot date (the day after the last date in the dataset)</span></span>
<span class="line">snapshot_date <span class="token operator">=</span> df<span class="token punctuation">[</span><span class="token string">'InvoiceDate'</span><span class="token punctuation">]</span><span class="token punctuation">.</span><span class="token builtin">max</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">+</span> pd<span class="token punctuation">.</span>Timedelta<span class="token punctuation">(</span>days<span class="token operator">=</span><span class="token number">1</span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"><span class="token comment"># Compute RFM metrics</span></span>
<span class="line">rfm <span class="token operator">=</span> df<span class="token punctuation">.</span>groupby<span class="token punctuation">(</span><span class="token string">'CustomerID'</span><span class="token punctuation">)</span><span class="token punctuation">.</span>agg<span class="token punctuation">(</span><span class="token punctuation">{</span></span>
<span class="line">    <span class="token string">'InvoiceDate'</span><span class="token punctuation">:</span> <span class="token keyword">lambda</span> x<span class="token punctuation">:</span> <span class="token punctuation">(</span>snapshot_date <span class="token operator">-</span> x<span class="token punctuation">.</span><span class="token builtin">max</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">.</span>days<span class="token punctuation">,</span>  <span class="token comment"># Recency</span></span>
<span class="line">    <span class="token string">'InvoiceNo'</span><span class="token punctuation">:</span> <span class="token string">'nunique'</span><span class="token punctuation">,</span>  <span class="token comment"># Frequency</span></span>
<span class="line">    <span class="token string">'TotalAmount'</span><span class="token punctuation">:</span> <span class="token string">'sum'</span>  <span class="token comment"># Monetary</span></span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"><span class="token comment"># Rename columns</span></span>
<span class="line">rfm<span class="token punctuation">.</span>columns <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token string">'Recency'</span><span class="token punctuation">,</span> <span class="token string">'Frequency'</span><span class="token punctuation">,</span> <span class="token string">'Monetary'</span><span class="token punctuation">]</span></span>
<span class="line"></span>
<span class="line"><span class="token comment"># View the RFM data</span></span>
<span class="line"><span class="token keyword">print</span><span class="token punctuation">(</span>rfm<span class="token punctuation">.</span>head<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token keyword">print</span><span class="token punctuation">(</span>rfm<span class="token punctuation">.</span>describe<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"><span class="token comment"># Visualize the RFM distributions</span></span>
<span class="line">plt<span class="token punctuation">.</span>figure<span class="token punctuation">(</span>figsize<span class="token operator">=</span><span class="token punctuation">(</span><span class="token number">15</span><span class="token punctuation">,</span> <span class="token number">5</span><span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line">plt<span class="token punctuation">.</span>subplot<span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">)</span></span>
<span class="line">sns<span class="token punctuation">.</span>histplot<span class="token punctuation">(</span>rfm<span class="token punctuation">[</span><span class="token string">'Recency'</span><span class="token punctuation">]</span><span class="token punctuation">,</span> bins<span class="token operator">=</span><span class="token number">30</span><span class="token punctuation">,</span> kde<span class="token operator">=</span><span class="token boolean">True</span><span class="token punctuation">)</span></span>
<span class="line">plt<span class="token punctuation">.</span>title<span class="token punctuation">(</span><span class="token string">'Recency Distribution'</span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line">plt<span class="token punctuation">.</span>subplot<span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">,</span> <span class="token number">2</span><span class="token punctuation">)</span></span>
<span class="line">sns<span class="token punctuation">.</span>histplot<span class="token punctuation">(</span>rfm<span class="token punctuation">[</span><span class="token string">'Frequency'</span><span class="token punctuation">]</span><span class="token punctuation">,</span> bins<span class="token operator">=</span><span class="token number">30</span><span class="token punctuation">,</span> kde<span class="token operator">=</span><span class="token boolean">True</span><span class="token punctuation">)</span></span>
<span class="line">plt<span class="token punctuation">.</span>title<span class="token punctuation">(</span><span class="token string">'Frequency Distribution'</span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line">plt<span class="token punctuation">.</span>subplot<span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">)</span></span>
<span class="line">sns<span class="token punctuation">.</span>histplot<span class="token punctuation">(</span>rfm<span class="token punctuation">[</span><span class="token string">'Monetary'</span><span class="token punctuation">]</span><span class="token punctuation">,</span> bins<span class="token operator">=</span><span class="token number">30</span><span class="token punctuation">,</span> kde<span class="token operator">=</span><span class="token boolean">True</span><span class="token punctuation">)</span></span>
<span class="line">plt<span class="token punctuation">.</span>title<span class="token punctuation">(</span><span class="token string">'Monetary Distribution'</span><span class="token punctuation">)</span></span>
<span class="line">plt<span class="token punctuation">.</span>tight_layout<span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">plt<span class="token punctuation">.</span>show<span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"><span class="token comment"># View correlations among RFM metrics</span></span>
<span class="line">plt<span class="token punctuation">.</span>figure<span class="token punctuation">(</span>figsize<span class="token operator">=</span><span class="token punctuation">(</span><span class="token number">10</span><span class="token punctuation">,</span> <span class="token number">8</span><span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line">sns<span class="token punctuation">.</span>heatmap<span class="token punctuation">(</span>rfm<span class="token punctuation">.</span>corr<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> annot<span class="token operator">=</span><span class="token boolean">True</span><span class="token punctuation">,</span> cmap<span class="token operator">=</span><span class="token string">'coolwarm'</span><span class="token punctuation">,</span> fmt<span class="token operator">=</span><span class="token string">'.2f'</span><span class="token punctuation">)</span></span>
<span class="line">plt<span class="token punctuation">.</span>title<span class="token punctuation">(</span><span class="token string">'Correlation Among RFM Metrics'</span><span class="token punctuation">)</span></span>
<span class="line">plt<span class="token punctuation">.</span>show<span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="step-3-feature-processing-and-standardization" tabindex="-1"><a class="header-anchor" href="#step-3-feature-processing-and-standardization"><span>Step 3: Feature Processing and Standardization</span></a></h3>
<p>Before applying clustering algorithms, we need to handle outliers and standardize the features.</p>
<div class="language-python line-numbers-mode" data-highlighter="prismjs" data-ext="py"><pre v-pre><code><span class="line"><span class="token comment"># Handle outliers</span></span>
<span class="line"><span class="token comment"># Use the IQR method to identify outliers</span></span>
<span class="line"><span class="token keyword">def</span> <span class="token function">remove_outliers</span><span class="token punctuation">(</span>df<span class="token punctuation">,</span> columns<span class="token punctuation">)</span><span class="token punctuation">:</span></span>
<span class="line">    df_clean <span class="token operator">=</span> df<span class="token punctuation">.</span>copy<span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token keyword">for</span> col <span class="token keyword">in</span> columns<span class="token punctuation">:</span></span>
<span class="line">        Q1 <span class="token operator">=</span> df_clean<span class="token punctuation">[</span>col<span class="token punctuation">]</span><span class="token punctuation">.</span>quantile<span class="token punctuation">(</span><span class="token number">0.25</span><span class="token punctuation">)</span></span>
<span class="line">        Q3 <span class="token operator">=</span> df_clean<span class="token punctuation">[</span>col<span class="token punctuation">]</span><span class="token punctuation">.</span>quantile<span class="token punctuation">(</span><span class="token number">0.75</span><span class="token punctuation">)</span></span>
<span class="line">        IQR <span class="token operator">=</span> Q3 <span class="token operator">-</span> Q1</span>
<span class="line">        lower_bound <span class="token operator">=</span> Q1 <span class="token operator">-</span> <span class="token number">1.5</span> <span class="token operator">*</span> IQR</span>
<span class="line">        upper_bound <span class="token operator">=</span> Q3 <span class="token operator">+</span> <span class="token number">1.5</span> <span class="token operator">*</span> IQR</span>
<span class="line">        df_clean <span class="token operator">=</span> df_clean<span class="token punctuation">[</span><span class="token punctuation">(</span>df_clean<span class="token punctuation">[</span>col<span class="token punctuation">]</span> <span class="token operator">>=</span> lower_bound<span class="token punctuation">)</span> <span class="token operator">&amp;</span> <span class="token punctuation">(</span>df_clean<span class="token punctuation">[</span>col<span class="token punctuation">]</span> <span class="token operator">&lt;=</span> upper_bound<span class="token punctuation">)</span><span class="token punctuation">]</span></span>
<span class="line">    <span class="token keyword">return</span> df_clean</span>
<span class="line"></span>
<span class="line"><span class="token comment"># Apply outlier removal</span></span>
<span class="line">rfm_clean <span class="token operator">=</span> remove_outliers<span class="token punctuation">(</span>rfm<span class="token punctuation">,</span> <span class="token punctuation">[</span><span class="token string">'Recency'</span><span class="token punctuation">,</span> <span class="token string">'Frequency'</span><span class="token punctuation">,</span> <span class="token string">'Monetary'</span><span class="token punctuation">]</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string-interpolation"><span class="token string">f"Rows before outlier removal: </span><span class="token interpolation"><span class="token punctuation">{</span>rfm<span class="token punctuation">.</span>shape<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">}</span></span><span class="token string">, after removal: </span><span class="token interpolation"><span class="token punctuation">{</span>rfm_clean<span class="token punctuation">.</span>shape<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">}</span></span><span class="token string">"</span></span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"><span class="token comment"># Log-transform to handle skewed distributions</span></span>
<span class="line">rfm_log <span class="token operator">=</span> rfm_clean<span class="token punctuation">.</span>copy<span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">rfm_log<span class="token punctuation">[</span><span class="token string">'Frequency'</span><span class="token punctuation">]</span> <span class="token operator">=</span> np<span class="token punctuation">.</span>log1p<span class="token punctuation">(</span>rfm_log<span class="token punctuation">[</span><span class="token string">'Frequency'</span><span class="token punctuation">]</span><span class="token punctuation">)</span></span>
<span class="line">rfm_log<span class="token punctuation">[</span><span class="token string">'Monetary'</span><span class="token punctuation">]</span> <span class="token operator">=</span> np<span class="token punctuation">.</span>log1p<span class="token punctuation">(</span>rfm_log<span class="token punctuation">[</span><span class="token string">'Monetary'</span><span class="token punctuation">]</span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"><span class="token comment"># Visualize the transformed distributions</span></span>
<span class="line">plt<span class="token punctuation">.</span>figure<span class="token punctuation">(</span>figsize<span class="token operator">=</span><span class="token punctuation">(</span><span class="token number">15</span><span class="token punctuation">,</span> <span class="token number">5</span><span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line">plt<span class="token punctuation">.</span>subplot<span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">)</span></span>
<span class="line">sns<span class="token punctuation">.</span>histplot<span class="token punctuation">(</span>rfm_log<span class="token punctuation">[</span><span class="token string">'Recency'</span><span class="token punctuation">]</span><span class="token punctuation">,</span> bins<span class="token operator">=</span><span class="token number">30</span><span class="token punctuation">,</span> kde<span class="token operator">=</span><span class="token boolean">True</span><span class="token punctuation">)</span></span>
<span class="line">plt<span class="token punctuation">.</span>title<span class="token punctuation">(</span><span class="token string">'Recency Distribution'</span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line">plt<span class="token punctuation">.</span>subplot<span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">,</span> <span class="token number">2</span><span class="token punctuation">)</span></span>
<span class="line">sns<span class="token punctuation">.</span>histplot<span class="token punctuation">(</span>rfm_log<span class="token punctuation">[</span><span class="token string">'Frequency'</span><span class="token punctuation">]</span><span class="token punctuation">,</span> bins<span class="token operator">=</span><span class="token number">30</span><span class="token punctuation">,</span> kde<span class="token operator">=</span><span class="token boolean">True</span><span class="token punctuation">)</span></span>
<span class="line">plt<span class="token punctuation">.</span>title<span class="token punctuation">(</span><span class="token string">'Log(Frequency) Distribution'</span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line">plt<span class="token punctuation">.</span>subplot<span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">)</span></span>
<span class="line">sns<span class="token punctuation">.</span>histplot<span class="token punctuation">(</span>rfm_log<span class="token punctuation">[</span><span class="token string">'Monetary'</span><span class="token punctuation">]</span><span class="token punctuation">,</span> bins<span class="token operator">=</span><span class="token number">30</span><span class="token punctuation">,</span> kde<span class="token operator">=</span><span class="token boolean">True</span><span class="token punctuation">)</span></span>
<span class="line">plt<span class="token punctuation">.</span>title<span class="token punctuation">(</span><span class="token string">'Log(Monetary) Distribution'</span><span class="token punctuation">)</span></span>
<span class="line">plt<span class="token punctuation">.</span>tight_layout<span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">plt<span class="token punctuation">.</span>show<span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"><span class="token comment"># Prepare features for clustering</span></span>
<span class="line">X <span class="token operator">=</span> rfm_log<span class="token punctuation">.</span>copy<span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">features <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token string">'Recency'</span><span class="token punctuation">,</span> <span class="token string">'Frequency'</span><span class="token punctuation">,</span> <span class="token string">'Monetary'</span><span class="token punctuation">]</span></span>
<span class="line"></span>
<span class="line"><span class="token comment"># Standardize features</span></span>
<span class="line">scaler <span class="token operator">=</span> StandardScaler<span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">X_scaled <span class="token operator">=</span> scaler<span class="token punctuation">.</span>fit_transform<span class="token punctuation">(</span>X<span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"><span class="token comment"># Convert back to DataFrame for analysis</span></span>
<span class="line">X_scaled_df <span class="token operator">=</span> pd<span class="token punctuation">.</span>DataFrame<span class="token punctuation">(</span>X_scaled<span class="token punctuation">,</span> index<span class="token operator">=</span>X<span class="token punctuation">.</span>index<span class="token punctuation">,</span> columns<span class="token operator">=</span>X<span class="token punctuation">.</span>columns<span class="token punctuation">)</span></span>
<span class="line"><span class="token keyword">print</span><span class="token punctuation">(</span>X_scaled_df<span class="token punctuation">.</span>head<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="step-4-determine-the-optimal-number-of-clusters" tabindex="-1"><a class="header-anchor" href="#step-4-determine-the-optimal-number-of-clusters"><span>Step 4: Determine the Optimal Number of Clusters</span></a></h3>
<p>Use the elbow method and silhouette scores to determine the best number of clusters.</p>
<div class="language-python line-numbers-mode" data-highlighter="prismjs" data-ext="py"><pre v-pre><code><span class="line"><span class="token comment"># Elbow method</span></span>
<span class="line">inertia <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">]</span></span>
<span class="line">silhouette_scores <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">]</span></span>
<span class="line">k_range <span class="token operator">=</span> <span class="token builtin">range</span><span class="token punctuation">(</span><span class="token number">2</span><span class="token punctuation">,</span> <span class="token number">11</span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">for</span> k <span class="token keyword">in</span> k_range<span class="token punctuation">:</span></span>
<span class="line">    kmeans <span class="token operator">=</span> KMeans<span class="token punctuation">(</span>n_clusters<span class="token operator">=</span>k<span class="token punctuation">,</span> random_state<span class="token operator">=</span><span class="token number">42</span><span class="token punctuation">,</span> n_init<span class="token operator">=</span><span class="token number">10</span><span class="token punctuation">)</span></span>
<span class="line">    kmeans<span class="token punctuation">.</span>fit<span class="token punctuation">(</span>X_scaled<span class="token punctuation">)</span></span>
<span class="line">    inertia<span class="token punctuation">.</span>append<span class="token punctuation">(</span>kmeans<span class="token punctuation">.</span>inertia_<span class="token punctuation">)</span></span>
<span class="line">    silhouette_scores<span class="token punctuation">.</span>append<span class="token punctuation">(</span>silhouette_score<span class="token punctuation">(</span>X_scaled<span class="token punctuation">,</span> kmeans<span class="token punctuation">.</span>labels_<span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"><span class="token comment"># Visualize the elbow method and silhouette scores</span></span>
<span class="line">plt<span class="token punctuation">.</span>figure<span class="token punctuation">(</span>figsize<span class="token operator">=</span><span class="token punctuation">(</span><span class="token number">12</span><span class="token punctuation">,</span> <span class="token number">5</span><span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line">plt<span class="token punctuation">.</span>subplot<span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">2</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">)</span></span>
<span class="line">plt<span class="token punctuation">.</span>plot<span class="token punctuation">(</span>k_range<span class="token punctuation">,</span> inertia<span class="token punctuation">,</span> <span class="token string">'o-'</span><span class="token punctuation">)</span></span>
<span class="line">plt<span class="token punctuation">.</span>xlabel<span class="token punctuation">(</span><span class="token string">'Number of Clusters (k)'</span><span class="token punctuation">)</span></span>
<span class="line">plt<span class="token punctuation">.</span>ylabel<span class="token punctuation">(</span><span class="token string">'Inertia'</span><span class="token punctuation">)</span></span>
<span class="line">plt<span class="token punctuation">.</span>title<span class="token punctuation">(</span><span class="token string">'Elbow Method'</span><span class="token punctuation">)</span></span>
<span class="line">plt<span class="token punctuation">.</span>grid<span class="token punctuation">(</span><span class="token boolean">True</span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line">plt<span class="token punctuation">.</span>subplot<span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">2</span><span class="token punctuation">,</span> <span class="token number">2</span><span class="token punctuation">)</span></span>
<span class="line">plt<span class="token punctuation">.</span>plot<span class="token punctuation">(</span>k_range<span class="token punctuation">,</span> silhouette_scores<span class="token punctuation">,</span> <span class="token string">'o-'</span><span class="token punctuation">)</span></span>
<span class="line">plt<span class="token punctuation">.</span>xlabel<span class="token punctuation">(</span><span class="token string">'Number of Clusters (k)'</span><span class="token punctuation">)</span></span>
<span class="line">plt<span class="token punctuation">.</span>ylabel<span class="token punctuation">(</span><span class="token string">'Silhouette Score'</span><span class="token punctuation">)</span></span>
<span class="line">plt<span class="token punctuation">.</span>title<span class="token punctuation">(</span><span class="token string">'Silhouette Score Method'</span><span class="token punctuation">)</span></span>
<span class="line">plt<span class="token punctuation">.</span>grid<span class="token punctuation">(</span><span class="token boolean">True</span><span class="token punctuation">)</span></span>
<span class="line">plt<span class="token punctuation">.</span>tight_layout<span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">plt<span class="token punctuation">.</span>show<span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"><span class="token comment"># Choose the optimal number of clusters based on the silhouette score</span></span>
<span class="line">best_k <span class="token operator">=</span> k_range<span class="token punctuation">[</span>silhouette_scores<span class="token punctuation">.</span>index<span class="token punctuation">(</span><span class="token builtin">max</span><span class="token punctuation">(</span>silhouette_scores<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">]</span></span>
<span class="line"><span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string-interpolation"><span class="token string">f"Optimal number of clusters (based on Silhouette Score): </span><span class="token interpolation"><span class="token punctuation">{</span>best_k<span class="token punctuation">}</span></span><span class="token string">"</span></span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="step-5-apply-k-means-clustering" tabindex="-1"><a class="header-anchor" href="#step-5-apply-k-means-clustering"><span>Step 5: Apply K-Means Clustering</span></a></h3>
<p>Apply K-Means clustering using the determined optimal number of clusters.</p>
<div class="language-python line-numbers-mode" data-highlighter="prismjs" data-ext="py"><pre v-pre><code><span class="line"><span class="token comment"># Apply K-Means clustering</span></span>
<span class="line">kmeans <span class="token operator">=</span> KMeans<span class="token punctuation">(</span>n_clusters<span class="token operator">=</span>best_k<span class="token punctuation">,</span> random_state<span class="token operator">=</span><span class="token number">42</span><span class="token punctuation">,</span> n_init<span class="token operator">=</span><span class="token number">10</span><span class="token punctuation">)</span></span>
<span class="line">rfm<span class="token punctuation">[</span><span class="token string">'Cluster'</span><span class="token punctuation">]</span> <span class="token operator">=</span> kmeans<span class="token punctuation">.</span>fit_predict<span class="token punctuation">(</span>X_scaled<span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"><span class="token comment"># View the size of each cluster</span></span>
<span class="line">cluster_sizes <span class="token operator">=</span> rfm<span class="token punctuation">[</span><span class="token string">'Cluster'</span><span class="token punctuation">]</span><span class="token punctuation">.</span>value_counts<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span>sort_index<span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">"Cluster Sizes:"</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token keyword">print</span><span class="token punctuation">(</span>cluster_sizes<span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"><span class="token comment"># Calculate cluster centers (in original scale)</span></span>
<span class="line">cluster_centers <span class="token operator">=</span> pd<span class="token punctuation">.</span>DataFrame<span class="token punctuation">(</span>scaler<span class="token punctuation">.</span>inverse_transform<span class="token punctuation">(</span>kmeans<span class="token punctuation">.</span>cluster_centers_<span class="token punctuation">)</span><span class="token punctuation">,</span> </span>
<span class="line">                              columns<span class="token operator">=</span>features<span class="token punctuation">)</span></span>
<span class="line">cluster_centers<span class="token punctuation">[</span><span class="token string">'Cluster'</span><span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token builtin">range</span><span class="token punctuation">(</span>best_k<span class="token punctuation">)</span></span>
<span class="line"><span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">"\nCluster Centers:"</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token keyword">print</span><span class="token punctuation">(</span>cluster_centers<span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"><span class="token comment"># Visualize clustering results using PCA to reduce dimensions to 2D</span></span>
<span class="line">pca <span class="token operator">=</span> PCA<span class="token punctuation">(</span>n_components<span class="token operator">=</span><span class="token number">2</span><span class="token punctuation">)</span></span>
<span class="line">X_pca <span class="token operator">=</span> pca<span class="token punctuation">.</span>fit_transform<span class="token punctuation">(</span>X_scaled<span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line">plt<span class="token punctuation">.</span>figure<span class="token punctuation">(</span>figsize<span class="token operator">=</span><span class="token punctuation">(</span><span class="token number">10</span><span class="token punctuation">,</span> <span class="token number">8</span><span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token keyword">for</span> i <span class="token keyword">in</span> <span class="token builtin">range</span><span class="token punctuation">(</span>best_k<span class="token punctuation">)</span><span class="token punctuation">:</span></span>
<span class="line">    plt<span class="token punctuation">.</span>scatter<span class="token punctuation">(</span>X_pca<span class="token punctuation">[</span>rfm<span class="token punctuation">[</span><span class="token string">'Cluster'</span><span class="token punctuation">]</span> <span class="token operator">==</span> i<span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">,</span> X_pca<span class="token punctuation">[</span>rfm<span class="token punctuation">[</span><span class="token string">'Cluster'</span><span class="token punctuation">]</span> <span class="token operator">==</span> i<span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">]</span><span class="token punctuation">,</span> label<span class="token operator">=</span><span class="token string-interpolation"><span class="token string">f'Cluster </span><span class="token interpolation"><span class="token punctuation">{</span>i<span class="token punctuation">}</span></span><span class="token string">'</span></span><span class="token punctuation">)</span></span>
<span class="line">plt<span class="token punctuation">.</span>scatter<span class="token punctuation">(</span>pca<span class="token punctuation">.</span>transform<span class="token punctuation">(</span>kmeans<span class="token punctuation">.</span>cluster_centers_<span class="token punctuation">)</span><span class="token punctuation">[</span><span class="token punctuation">:</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">,</span> pca<span class="token punctuation">.</span>transform<span class="token punctuation">(</span>kmeans<span class="token punctuation">.</span>cluster_centers_<span class="token punctuation">)</span><span class="token punctuation">[</span><span class="token punctuation">:</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">]</span><span class="token punctuation">,</span> </span>
<span class="line">            s<span class="token operator">=</span><span class="token number">300</span><span class="token punctuation">,</span> c<span class="token operator">=</span><span class="token string">'red'</span><span class="token punctuation">,</span> marker<span class="token operator">=</span><span class="token string">'X'</span><span class="token punctuation">,</span> label<span class="token operator">=</span><span class="token string">'Centroids'</span><span class="token punctuation">)</span></span>
<span class="line">plt<span class="token punctuation">.</span>title<span class="token punctuation">(</span><span class="token string">'Customer Segmentation (PCA Visualization)'</span><span class="token punctuation">)</span></span>
<span class="line">plt<span class="token punctuation">.</span>xlabel<span class="token punctuation">(</span><span class="token string">'Principal Component 1'</span><span class="token punctuation">)</span></span>
<span class="line">plt<span class="token punctuation">.</span>ylabel<span class="token punctuation">(</span><span class="token string">'Principal Component 2'</span><span class="token punctuation">)</span></span>
<span class="line">plt<span class="token punctuation">.</span>legend<span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">plt<span class="token punctuation">.</span>grid<span class="token punctuation">(</span><span class="token boolean">True</span><span class="token punctuation">)</span></span>
<span class="line">plt<span class="token punctuation">.</span>show<span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="step-6-analyze-customer-group-characteristics" tabindex="-1"><a class="header-anchor" href="#step-6-analyze-customer-group-characteristics"><span>Step 6: Analyze Customer Group Characteristics</span></a></h3>
<p>Analyze the characteristics of each customer group and provide business recommendations.</p>
<div class="language-python line-numbers-mode" data-highlighter="prismjs" data-ext="py"><pre v-pre><code><span class="line"><span class="token comment"># Analyze the RFM characteristics for each cluster</span></span>
<span class="line">cluster_analysis <span class="token operator">=</span> rfm<span class="token punctuation">.</span>groupby<span class="token punctuation">(</span><span class="token string">'Cluster'</span><span class="token punctuation">)</span><span class="token punctuation">.</span>agg<span class="token punctuation">(</span><span class="token punctuation">{</span></span>
<span class="line">    <span class="token string">'Recency'</span><span class="token punctuation">:</span> <span class="token string">'mean'</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string">'Frequency'</span><span class="token punctuation">:</span> <span class="token string">'mean'</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string">'Monetary'</span><span class="token punctuation">:</span> <span class="token string">'mean'</span></span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">.</span>reset_index<span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"><span class="token comment"># Visualize the characteristics for each cluster</span></span>
<span class="line">plt<span class="token punctuation">.</span>figure<span class="token punctuation">(</span>figsize<span class="token operator">=</span><span class="token punctuation">(</span><span class="token number">15</span><span class="token punctuation">,</span> <span class="token number">5</span><span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line">plt<span class="token punctuation">.</span>subplot<span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">)</span></span>
<span class="line">sns<span class="token punctuation">.</span>barplot<span class="token punctuation">(</span>x<span class="token operator">=</span><span class="token string">'Cluster'</span><span class="token punctuation">,</span> y<span class="token operator">=</span><span class="token string">'Recency'</span><span class="token punctuation">,</span> data<span class="token operator">=</span>cluster_analysis<span class="token punctuation">)</span></span>
<span class="line">plt<span class="token punctuation">.</span>title<span class="token punctuation">(</span><span class="token string">'Average Recency per Cluster'</span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line">plt<span class="token punctuation">.</span>subplot<span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">,</span> <span class="token number">2</span><span class="token punctuation">)</span></span>
<span class="line">sns<span class="token punctuation">.</span>barplot<span class="token punctuation">(</span>x<span class="token operator">=</span><span class="token string">'Cluster'</span><span class="token punctuation">,</span> y<span class="token operator">=</span><span class="token string">'Frequency'</span><span class="token punctuation">,</span> data<span class="token operator">=</span>cluster_analysis<span class="token punctuation">)</span></span>
<span class="line">plt<span class="token punctuation">.</span>title<span class="token punctuation">(</span><span class="token string">'Average Frequency per Cluster'</span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line">plt<span class="token punctuation">.</span>subplot<span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">)</span></span>
<span class="line">sns<span class="token punctuation">.</span>barplot<span class="token punctuation">(</span>x<span class="token operator">=</span><span class="token string">'Cluster'</span><span class="token punctuation">,</span> y<span class="token operator">=</span><span class="token string">'Monetary'</span><span class="token punctuation">,</span> data<span class="token operator">=</span>cluster_analysis<span class="token punctuation">)</span></span>
<span class="line">plt<span class="token punctuation">.</span>title<span class="token punctuation">(</span><span class="token string">'Average Monetary Value per Cluster'</span><span class="token punctuation">)</span></span>
<span class="line">plt<span class="token punctuation">.</span>tight_layout<span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">plt<span class="token punctuation">.</span>show<span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"><span class="token comment"># Radar chart visualization for cluster characteristics</span></span>
<span class="line"><span class="token keyword">from</span> math <span class="token keyword">import</span> pi</span>
<span class="line"></span>
<span class="line"><span class="token comment"># Normalize data for radar chart</span></span>
<span class="line">radar_df <span class="token operator">=</span> cluster_analysis<span class="token punctuation">.</span>copy<span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token keyword">for</span> feature <span class="token keyword">in</span> features<span class="token punctuation">:</span></span>
<span class="line">    radar_df<span class="token punctuation">[</span>feature<span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token punctuation">(</span>radar_df<span class="token punctuation">[</span>feature<span class="token punctuation">]</span> <span class="token operator">-</span> radar_df<span class="token punctuation">[</span>feature<span class="token punctuation">]</span><span class="token punctuation">.</span><span class="token builtin">min</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token operator">/</span> <span class="token punctuation">(</span>radar_df<span class="token punctuation">[</span>feature<span class="token punctuation">]</span><span class="token punctuation">.</span><span class="token builtin">max</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">-</span> radar_df<span class="token punctuation">[</span>feature<span class="token punctuation">]</span><span class="token punctuation">.</span><span class="token builtin">min</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token comment"># For Recency, lower is better so we invert the values</span></span>
<span class="line">    <span class="token keyword">if</span> feature <span class="token operator">==</span> <span class="token string">'Recency'</span><span class="token punctuation">:</span></span>
<span class="line">        radar_df<span class="token punctuation">[</span>feature<span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token number">1</span> <span class="token operator">-</span> radar_df<span class="token punctuation">[</span>feature<span class="token punctuation">]</span></span>
<span class="line"></span>
<span class="line"><span class="token comment"># Set up radar chart</span></span>
<span class="line">categories <span class="token operator">=</span> features</span>
<span class="line">N <span class="token operator">=</span> <span class="token builtin">len</span><span class="token punctuation">(</span>categories<span class="token punctuation">)</span></span>
<span class="line">angles <span class="token operator">=</span> <span class="token punctuation">[</span>n <span class="token operator">/</span> <span class="token builtin">float</span><span class="token punctuation">(</span>N<span class="token punctuation">)</span> <span class="token operator">*</span> <span class="token number">2</span> <span class="token operator">*</span> pi <span class="token keyword">for</span> n <span class="token keyword">in</span> <span class="token builtin">range</span><span class="token punctuation">(</span>N<span class="token punctuation">)</span><span class="token punctuation">]</span></span>
<span class="line">angles <span class="token operator">+=</span> angles<span class="token punctuation">[</span><span class="token punctuation">:</span><span class="token number">1</span><span class="token punctuation">]</span></span>
<span class="line"></span>
<span class="line">plt<span class="token punctuation">.</span>figure<span class="token punctuation">(</span>figsize<span class="token operator">=</span><span class="token punctuation">(</span><span class="token number">12</span><span class="token punctuation">,</span> <span class="token number">10</span><span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line">ax <span class="token operator">=</span> plt<span class="token punctuation">.</span>subplot<span class="token punctuation">(</span><span class="token number">111</span><span class="token punctuation">,</span> polar<span class="token operator">=</span><span class="token boolean">True</span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">for</span> i<span class="token punctuation">,</span> cluster <span class="token keyword">in</span> <span class="token builtin">enumerate</span><span class="token punctuation">(</span>radar_df<span class="token punctuation">[</span><span class="token string">'Cluster'</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">:</span></span>
<span class="line">    values <span class="token operator">=</span> radar_df<span class="token punctuation">.</span>loc<span class="token punctuation">[</span>radar_df<span class="token punctuation">[</span><span class="token string">'Cluster'</span><span class="token punctuation">]</span> <span class="token operator">==</span> cluster<span class="token punctuation">,</span> features<span class="token punctuation">]</span><span class="token punctuation">.</span>values<span class="token punctuation">.</span>flatten<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span>tolist<span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">    values <span class="token operator">+=</span> values<span class="token punctuation">[</span><span class="token punctuation">:</span><span class="token number">1</span><span class="token punctuation">]</span></span>
<span class="line">    ax<span class="token punctuation">.</span>plot<span class="token punctuation">(</span>angles<span class="token punctuation">,</span> values<span class="token punctuation">,</span> linewidth<span class="token operator">=</span><span class="token number">2</span><span class="token punctuation">,</span> linestyle<span class="token operator">=</span><span class="token string">'solid'</span><span class="token punctuation">,</span> label<span class="token operator">=</span><span class="token string-interpolation"><span class="token string">f'Cluster </span><span class="token interpolation"><span class="token punctuation">{</span>cluster<span class="token punctuation">}</span></span><span class="token string">'</span></span><span class="token punctuation">)</span></span>
<span class="line">    ax<span class="token punctuation">.</span>fill<span class="token punctuation">(</span>angles<span class="token punctuation">,</span> values<span class="token punctuation">,</span> alpha<span class="token operator">=</span><span class="token number">0.1</span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line">plt<span class="token punctuation">.</span>xticks<span class="token punctuation">(</span>angles<span class="token punctuation">[</span><span class="token punctuation">:</span><span class="token operator">-</span><span class="token number">1</span><span class="token punctuation">]</span><span class="token punctuation">,</span> categories<span class="token punctuation">)</span></span>
<span class="line">plt<span class="token punctuation">.</span>yticks<span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token number">0.2</span><span class="token punctuation">,</span> <span class="token number">0.4</span><span class="token punctuation">,</span> <span class="token number">0.6</span><span class="token punctuation">,</span> <span class="token number">0.8</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token punctuation">[</span><span class="token string">"0.2"</span><span class="token punctuation">,</span> <span class="token string">"0.4"</span><span class="token punctuation">,</span> <span class="token string">"0.6"</span><span class="token punctuation">,</span> <span class="token string">"0.8"</span><span class="token punctuation">]</span><span class="token punctuation">,</span> color<span class="token operator">=</span><span class="token string">"grey"</span><span class="token punctuation">,</span> size<span class="token operator">=</span><span class="token number">8</span><span class="token punctuation">)</span></span>
<span class="line">plt<span class="token punctuation">.</span>legend<span class="token punctuation">(</span>loc<span class="token operator">=</span><span class="token string">'upper right'</span><span class="token punctuation">,</span> bbox_to_anchor<span class="token operator">=</span><span class="token punctuation">(</span><span class="token number">0.1</span><span class="token punctuation">,</span> <span class="token number">0.1</span><span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line">plt<span class="token punctuation">.</span>title<span class="token punctuation">(</span><span class="token string">'Radar Chart of Customer Group Characteristics'</span><span class="token punctuation">)</span></span>
<span class="line">plt<span class="token punctuation">.</span>show<span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"><span class="token comment"># Naming the customer segments and providing business recommendations</span></span>
<span class="line">cluster_names <span class="token operator">=</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token number">0</span><span class="token punctuation">:</span> <span class="token string">"High-Value Loyal Customers"</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token number">1</span><span class="token punctuation">:</span> <span class="token string">"Potential Customers"</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token number">2</span><span class="token punctuation">:</span> <span class="token string">"Dormant Customers"</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token number">3</span><span class="token punctuation">:</span> <span class="token string">"New Customers"</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line">business_recommendations <span class="token operator">=</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token number">0</span><span class="token punctuation">:</span> <span class="token string">"Offer VIP services, send personalized discounts, and encourage referrals."</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token number">1</span><span class="token punctuation">:</span> <span class="token string">"Provide purchase incentives, increase purchase frequency, and recommend related products."</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token number">2</span><span class="token punctuation">:</span> <span class="token string">"Send reactivation emails, offer special discounts, and understand reasons for churn."</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token number">3</span><span class="token punctuation">:</span> <span class="token string">"Provide a good first experience, encourage a second purchase, and collect feedback."</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line"><span class="token comment"># Create the final customer segmentation report</span></span>
<span class="line">cluster_report <span class="token operator">=</span> pd<span class="token punctuation">.</span>DataFrame<span class="token punctuation">(</span><span class="token punctuation">{</span></span>
<span class="line">    <span class="token string">'Cluster'</span><span class="token punctuation">:</span> <span class="token builtin">range</span><span class="token punctuation">(</span>best_k<span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string">'Name'</span><span class="token punctuation">:</span> <span class="token punctuation">[</span>cluster_names<span class="token punctuation">.</span>get<span class="token punctuation">(</span>i<span class="token punctuation">,</span> <span class="token string-interpolation"><span class="token string">f"Cluster </span><span class="token interpolation"><span class="token punctuation">{</span>i<span class="token punctuation">}</span></span><span class="token string">"</span></span><span class="token punctuation">)</span> <span class="token keyword">for</span> i <span class="token keyword">in</span> <span class="token builtin">range</span><span class="token punctuation">(</span>best_k<span class="token punctuation">)</span><span class="token punctuation">]</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string">'Size'</span><span class="token punctuation">:</span> cluster_sizes<span class="token punctuation">.</span>values<span class="token punctuation">,</span></span>
<span class="line">    <span class="token string">'Recency'</span><span class="token punctuation">:</span> cluster_analysis<span class="token punctuation">[</span><span class="token string">'Recency'</span><span class="token punctuation">]</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string">'Frequency'</span><span class="token punctuation">:</span> cluster_analysis<span class="token punctuation">[</span><span class="token string">'Frequency'</span><span class="token punctuation">]</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string">'Monetary'</span><span class="token punctuation">:</span> cluster_analysis<span class="token punctuation">[</span><span class="token string">'Monetary'</span><span class="token punctuation">]</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string">'Business Recommendations'</span><span class="token punctuation">:</span> <span class="token punctuation">[</span>business_recommendations<span class="token punctuation">.</span>get<span class="token punctuation">(</span>i<span class="token punctuation">,</span> <span class="token string">""</span><span class="token punctuation">)</span> <span class="token keyword">for</span> i <span class="token keyword">in</span> <span class="token builtin">range</span><span class="token punctuation">(</span>best_k<span class="token punctuation">)</span><span class="token punctuation">]</span></span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">"Customer Segmentation Report:"</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token keyword">print</span><span class="token punctuation">(</span>cluster_report<span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="results-analysis" tabindex="-1"><a class="header-anchor" href="#results-analysis"><span>Results Analysis</span></a></h2>
<p>Through the K-Means clustering algorithm, we successfully segmented customers into distinct groups, each with different purchasing behavior characteristics:</p>
<ol>
<li><strong>High-Value Loyal Customers</strong>: These customers have made recent purchases, exhibit high purchase frequency, and spend a large amount. They are the core customer group contributing most to revenue.</li>
<li><strong>Potential Customers</strong>: These customers show moderate purchase frequency and spending, and have the potential to become high-value customers.</li>
<li><strong>Dormant Customers</strong>: These customers have not purchased for a long time despite previously good purchasing records. They are targets for reactivation campaigns.</li>
<li><strong>New Customers</strong>: These customers have only recently started purchasing, with low frequency and spending. Special attention is needed to improve retention.</li>
</ol>
<p>This customer segmentation helps businesses formulate targeted marketing strategies, improve customer satisfaction and loyalty, and ultimately enhance sales performance and customer lifetime value.</p>
<h2 id="advanced-challenges" tabindex="-1"><a class="header-anchor" href="#advanced-challenges"><span>Advanced Challenges</span></a></h2>
<p>If you have completed the basic tasks, you can try the following advanced challenges:</p>
<ol>
<li><strong>Expand the Feature Set</strong>: In addition to RFM indicators, try incorporating features such as product category preferences and purchasing time patterns.</li>
<li><strong>Try Other Clustering Algorithms</strong>: Compare the results of hierarchical clustering, DBSCAN, and other methods with K-Means.</li>
<li><strong>Time Series Analysis</strong>: Analyze how customer segments change over time to identify migration patterns.</li>
<li><strong>Predictive Models</strong>: Build churn prediction or next-purchase prediction models based on the segmentation results.</li>
<li><strong>Recommendation Systems</strong>: Develop tailored product recommendation strategies for each customer segment.</li>
</ol>
<h2 id="summary-and-reflection" tabindex="-1"><a class="header-anchor" href="#summary-and-reflection"><span>Summary and Reflection</span></a></h2>
<p>Through this project, we learned how to use clustering algorithms to segment customers and extract valuable business insights from data. Customer segmentation is a powerful tool for understanding customer behavior and preferences, helping businesses optimize marketing strategies, improve customer satisfaction and loyalty. In practice, segmentation should be an ongoing process—updated regularly as new data accumulates and the business environment changes. Moreover, interpreting and applying segmentation results must be aligned with specific business contexts and objectives to maximize value.</p>
<h3 id="questions-for-reflection" tabindex="-1"><a class="header-anchor" href="#questions-for-reflection"><span>Questions for Reflection</span></a></h3>
<ol>
<li>Besides RFM indicators, what other customer features might be valuable for segmentation? How can these features be obtained and integrated?</li>
<li>How might customer segmentation differ across industries? For example, which indicators should be prioritized for segmentation in e-commerce, financial services, and content subscription services?</li>
<li>How can the business value of customer segmentation be evaluated? What metrics can be used to measure the effectiveness of segmentation strategies?</li>
</ol>
<div class="practice-link">
  <a href="/en/projects/clustering/image-segmentation.html" class="button">Next Project: Image Color Segmentation</a>
</div>
</div></template>


